/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qutoes;



import java.io.FileReader;
import java.util.ArrayList;
import com.google.gson.Gson;
import qutoes.Qutos;


public class App {


    public static void main(String[] args) {
        String path ="C:\\Users\\STUDENT\\401java\\quotes\\app\\src\\main\\resources\\data.json";

        getQuote(path);


    }

    public static void getQuote(String path){
        // create Gson instance
        Gson gson = new Gson();
        FileReader fileReader = null;
        try {
            // create a reader
            fileReader = new FileReader(path);
            Qutos[] quotes = gson.fromJson(fileReader, Qutos[].class);
            int randomQuote = (int)(Math.random() * quotes.length);

            System.out.println(quotes[randomQuote]);
            //  System.out.println(quotes[randomQuote].text);

            // close reader
            fileReader.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}