/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qutoes;

import com.google.gson.Gson;
import org.junit.jupiter.api.Test;

import java.io.FileNotFoundException;
import java.io.FileReader;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void testreturnelements() throws FileNotFoundException {
        String path="C:\\Users\\STUDENT\\401java\\quotes\\app\\src\\main\\resources\\data.json";
        Gson gson = new Gson();
        FileReader fileReader = null;
        fileReader = new FileReader(path);
        Qutos[] quotes = gson.fromJson(fileReader, Qutos[].class);
        int randomQuote = (int)(Math.random() * quotes.length);
        Boolean isreturend=false;

        if(quotes[randomQuote].text !="" && quotes[randomQuote].likes !="" && quotes[randomQuote].author !=""){
            isreturend=true;
        }
        assertEquals(true,isreturend);

    }
}
